language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
env:
  global:
    secure: rrfORhXJmnsuzOJH+bNGCOOjCS+V3Wx8XWf0KMJKpbhO9Y2VSuUxxdm12IcP3J4GsYonnixkXGvCzchvRpjPhbSWSGhwJHNosE7F/YZDGUK+zniGlX0Kv+k4sMW6/DrzHmX31laQA8SK6W/o2An/yAQ8bDklVGdUfIjjm6OymkxBt0SJ+jry0dIZ71No5r96U7aWmI4gfQxdfqJnlPKylbfrkF/vh0tkyaJzSyfCXiTj/q4F84A2sBAqltIzDEMixGXiOVZxFCw/ChwfbfuVQ3WHWMHDKMqIgRrYiRiqt+ufj0uEwL5CceF/eg66wx7d3az4P3l978d0YygkWcpxkLsIaClKe3oZxhXn9C3MMYIrtvL0GjCOKbNB2Edc8wzliQPd14iRxUkgfexmhnmECbAgB00X8SEhan0eH87IANAEi/vw+KYSYAzaWbgB25W+JZTudSvWEzSDjjrnfBo1fDhe3DXWumab09G/PlxTv3sVZgWz/l0le/wXRzRbWJa7ZQd4PzrVKNvDWmhzY19hfo7Y9JQKVdzKRgC5PNOtGs+txTZw4QY63LGaxkHKf/haWeaF0acPSA5U7rt87+uL1bTP3VLz6cwm0oAogW7TJn7D/KEat0OXiJ/XtLbuSDptqqL65ZUFWO14mcPbH8tGicnZ8DLISEbywNc/jJXPEuY=